apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-wordpress
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress"
