apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-wordpress-dev-pv-cr
rules:
- apiGroups:
  - "*"
  resources:
  - persistentvolumes
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-wordpress-dev-pv-crb
subjects:
- kind: User
  name: wordpress-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-wordpress-dev-pv-cr  
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-wordpress-dev-r
  namespace: wordpress
rules:
- apiGroups:
  - "*"
  resources:
  - persistentvolumeclaims
  - pods
  - deployments
  - secrets
  - services 
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-wordpress-dev-rb
  namespace: wordpress
subjects:
- kind: User
  name: wordpress-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Release.Name }}-wordpress-dev-r
  apiGroup: rbac.authorization.k8s.io

---


kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: wordpress
  name: {{ .Release.Name }}-wordpress-pf-r
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/portforward", "deployments", "services"]
  verbs: ["get", "list", "create"]



---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-wordpress-pf-rb
  namespace: wordpress
subjects:
- kind: User
  name: wordpress-pf
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Release.Name }}-wordpress-pf-r
  apiGroup: ""
